import localFont from "next/font/local";
import "./globals.css";
import "./commenStyle.css"
import 'toastr/build/toastr.min.css';
import { Inter } from 'next/font/google';
import { Pacifico } from 'next/font/google';

const pacifico = Pacifico({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-pacifico',
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={`${pacifico.variable} antialiased`} style={{ fontFamily: 'var(--font-pacifico)' }}>

        {children}
      </body>
    </html>
  );
}
